# Generated by Django 5.2.5 on 2026-06-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When media was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Moved to trash'),
        ),
        migrations.AddField(
            model_name='media',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Marked as favorite by user'),
        ),
    ]
